module.exports = {
  FIND_USER: 'SELECT * from Users where id = ?',
  // NOTES
  FIND_COLUMNS_BY_USER_ID: 'SELECT * from Columns where owner_id = ? order by position',
  GET_NOTE_TOP_POSITION: 'SELECT COUNT(*) FROM Notes WHERE column_id = ?',
  CREATE_NOTE: 'INSERT INTO Notes (position, text, writer_id, column_id) VALUES (?, ?, ?, ?)',
  GET_LAST_INSERTED_NOTE: 'select * from Notes where created_at in (SELECT max(N.created_at) as created_at from Notes N left join Columns C on C.id = N.column_id WHERE owner_id = ?)',
  FIND_NOTE: 'SELECT * from Notes where id = ?',
  UPDATE_NOTE_TEXT: 'UPDATE Notes SET text = ? WHERE id = ?',
  FIND_NOTE_BY_POSITION: 'SELECT * from Notes where column_id = ? and position = ?',
  UPDATE_NOTE_POSITION: 'UPDATE Notes SET column_id = ?, position = ? WHERE id = ?',
  DELETE_NOTE: 'DELETE FROM Notes WHERE id = ?',
  INCREASE_NOTE_POSITION: 'UPDATE Notes SET position = position + 1 WHERE column_id = ? and position >= ?',
  DECREASE_NOTE_POSITION: 'UPDATE Notes SET position = position - 1 WHERE column_id = ? and position >= ?',
  // COLUMNS
  FIND_COLUMN: 'SELECT * from Columns where id = ?',
  FIND_NOTES_IN_COLUMN: 'SELECT * from Notes where column_id = ? order by position',
  FIND_COLUMN_BY_POSITION: 'SELECT * from Columns where owner_id = ? and position = ?',
  UPDATE_COLUMN_TITLE: 'UPDATE Columns SET title = ? WHERE id = ?',
  UPDATE_COLUMN_POSITION: 'UPDATE Columns SET position = ? WHERE id = ?',
  DELETE_COLUMN: 'DELETE FROM Columns WHERE id = ?',
  CREATE_COLUMN: 'INSERT INTO Columns (title, owner_id, writer_id, position) VALUES (?, ?, ?, ?)',
  GET_LAST_INSERTED_COLUMN: 'SELECT * FROM Columns WHERE created_at in (SELECT max(created_at) from Columns WHERE owner_id = ?)',
  GET_COLUMN_LAST_POSITION: 'SELECT COUNT(*) FROM Columns WHERE owner_id = ?',
  INCREASE_COLUMN_POSITION: 'UPDATE Columns SET position = position + 1 WHERE owner_id = ? and position >= ?',
  DECREASE_COLUMN_POSITION: 'UPDATE Columns SET position = position - 1 WHERE owner_id = ? and position >= ?',
};
